## Notes:
# Stereolabs Repository: https://github.com/stereolabs/zed-sdk
#
# This script was mostly generated by AI using the Stereolabs' examples.
# The idea is to check whether or not the camera works with Jetson AGX Orin.

import sys
import cv2
import numpy as np
import pyzed.sl as sl

def main():
    # Create a Camera object
    zed = sl.Camera()

    # Configure initialization parameters
    init_params = sl.InitParameters()
    init_params.camera_resolution = sl.RESOLUTION.HD720  # Options: HD2K, HD1080, HD720, VGA
    init_params.camera_fps = 30                          # Set frame rate
    init_params.depth_mode = sl.DEPTH_MODE.ULTRA         # Options: ULTRA, QUALITY, PERFORMANCE, NEURAL
    init_params.coordinate_units = sl.UNIT.METER         # Use meters for depth values

    # Open the camera
    status = zed.open(init_params)
    if status != sl.ERROR_CODE.SUCCESS:
        print(f"Failed to open ZED camera: {status}")
        sys.exit(1)

    # Create runtime parameters
    runtime_params = sl.RuntimeParameters()

    # Allocate containers for the data
    image_left = sl.Mat()
    depth_image = sl.Mat()

    print("Camera initialized. Press 'q' in the graphics window to exit.")

    try:
        while True:
            # Grab a new frame
            if zed.grab(runtime_params) == sl.ERROR_CODE.SUCCESS:
                # Retrieve the left RGB image
                zed.retrieve_image(image_left, sl.VIEW.LEFT)
                # Retrieve the colored depth visualization
                zed.retrieve_image(depth_image, sl.VIEW.DEPTH)

                # Convert sl.Mat to numpy arrays for OpenCV
                frame_rgb = image_left.get_data()
                frame_depth = depth_image.get_data()

                # Slice away the alpha channel (BGRA -> BGR) so they match standard formats
                frame_rgb_bgr = cv2.cvtColor(frame_rgb, cv2.COLOR_RGBA2BGR)
                frame_depth_bgr = cv2.cvtColor(frame_depth, cv2.COLOR_RGBA2BGR)

                # Stack the images horizontally to see them side-by-side
                combined_view = np.hstack((frame_rgb_bgr, frame_depth_bgr))

                # Display the result
                cv2.imshow("ZED 2i - Left Feed | Depth Map", combined_view)

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

    finally:
        # Close the camera and destroy windows safely
        zed.close()
        cv2.destroyAllWindows()
        print("Camera closed successfully.")

if __name__ == "__main__":
    main()